---
# RETART THE RUST SERVER
- name: Start the Rust Service
  systemd:
    name: rust-server
    state: restarted
    daemon_reload: yes
  register: rustrestarted
  tags:
    - never
    - restart

- name: Show Rust Status
  debug:
    var: ruststarted
  tags:
    - never
    - restart
