- name: Configure Firewall rules
  become: yes
  block:
    - ufw:
        state: enabled
        policy: allow

    - ufw:
        logging: on

    - ufw:
        rule: allow
        port: ssh

    - name: Allow NFS hosts
      ufw:
        rule: allow
        port: "{{ mcs_rcon_port }}"
        #src: "{{ item.host}}/32"
        proto: any
      #loop: "{{  }}"